from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime
from functools import partial
from typing import Any

from homeassistant.components.recorder import history
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import UnitOfEnergy
from homeassistant.core import HomeAssistant, State, callback
from homeassistant.helpers.event import async_track_time_change
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util
from homeassistant.util import slugify

from .const import (
    CONF_GRID_ENERGY,
    CONF_HOUSE_ENERGY,
    CONF_NAME_PREFIX,
    INTERVAL_HOURS,
    INTERVAL_MINUTES,
    MAX_INTERVAL_DRIFT_SECONDS,
    STORE_KEY_PREFIX,
    STORE_VERSION,
)


# Base object IDs generated by sensor.py when no prefix is configured.
# With a prefix, Home Assistant prepends the slugified prefix to these names.
HISTORY_FIELD_OBJECT_IDS: dict[str, str] = {
    "grid_power_kw": "grid_power_15_min",
    "house_power_kw": "house_power_15_min",
    "reduction_kw": "grid_reduction_15_min",
    "reduction_percent": "grid_reduction_15_min_percent",
    "grid_peak_kw": "grid_power_peak_month",
    "grid_peak_house_kw": "house_power_at_grid_peak",
    "grid_peak_reduction_kw": "grid_reduction_at_grid_peak",
    "grid_peak_reduction_percent": "grid_reduction_at_grid_peak_percent",
    "house_peak_kw": "house_power_peak_month",
    "house_peak_grid_kw": "grid_power_at_house_peak",
    "house_peak_reduction_kw": "grid_reduction_at_house_peak",
    "house_peak_reduction_percent": "grid_reduction_at_house_peak_percent",
}

GRID_PEAK_OBJECT_ID = "grid_power_peak_month"
HOUSE_PEAK_OBJECT_ID = "house_power_peak_month"
CURRENT_INTERVAL_OBJECT_ID = "grid_power_15_min"

@dataclass
class AnalysisState:
    last_timestamp: str | None = None
    last_grid_energy_kwh: float | None = None
    last_house_energy_kwh: float | None = None
    grid_power_kw: float | None = None
    house_power_kw: float | None = None
    reduction_kw: float | None = None
    reduction_percent: float | None = None
    interval_start: str | None = None
    interval_end: str | None = None
    grid_peak_kw: float | None = None
    grid_peak_time: str | None = None
    grid_peak_house_kw: float | None = None
    grid_peak_reduction_kw: float | None = None
    grid_peak_reduction_percent: float | None = None
    house_peak_kw: float | None = None
    house_peak_time: str | None = None
    house_peak_grid_kw: float | None = None
    house_peak_reduction_kw: float | None = None
    house_peak_reduction_percent: float | None = None
    peak_month: str | None = None
    invalid_intervals: int = 0
    restored_from_history: bool = False
    restored_at: str | None = None
    configured_grid_energy: str | None = None
    configured_house_energy: str | None = None
    grid_source_changed_at: str | None = None
    house_source_changed_at: str | None = None


class QuarterHourPowerCoordinator:
    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        self.hass = hass
        self.entry = entry
        self.grid_entity = entry.options.get(
            CONF_GRID_ENERGY, entry.data[CONF_GRID_ENERGY]
        )
        self.house_entity = entry.options.get(
            CONF_HOUSE_ENERGY, entry.data.get(CONF_HOUSE_ENERGY)
        ) or None
        self.name_prefix = entry.options.get(
            CONF_NAME_PREFIX, entry.data.get(CONF_NAME_PREFIX, "")
        ).strip()
        self.state = AnalysisState()
        self.listeners: list[Any] = []
        self._remove_timer = None
        self._store = Store(hass, STORE_VERSION, f"{STORE_KEY_PREFIX}.{entry.entry_id}")

    async def async_initialize(self) -> None:
        stored = await self._store.async_load()
        stored_keys: set[str] = set()
        if isinstance(stored, dict):
            stored_keys = set(stored)
            allowed = AnalysisState.__dataclass_fields__.keys()
            self.state = AnalysisState(**{k: v for k, v in stored.items() if k in allowed})

        now = dt_util.now().replace(microsecond=0)
        current_month = now.strftime("%Y-%m")

        # Version 0.1.4 stores the configured source entities in the state.
        # When upgrading from an older version those fields are missing; treat
        # the current entities as the existing sources so a normal upgrade does
        # not unnecessarily discard an otherwise valid baseline. In 0.1.5,
        # configured_house_energy=None is a valid persisted value, so check for
        # key presence rather than checking the value itself.
        if "configured_grid_energy" not in stored_keys:
            self.state.configured_grid_energy = self.grid_entity
        if "configured_house_energy" not in stored_keys:
            self.state.configured_house_energy = self.house_entity

        source_changed = self._handle_source_changes(now)

        # A normal HA restart keeps the Store and therefore needs no recovery.
        # If the integration was deleted and re-added, a new config-entry ID
        # means a new Store. Recorder history, however, still exists under the
        # same entity IDs, so restore the current month from that history.
        if self.state.peak_month != current_month:
            restored = await self._async_restore_from_recorder(now)
            if not restored:
                self._reset_month(current_month)

        # Source changes intentionally preserve the current month's peaks, but
        # the old source baseline/current interval must never be mixed with the
        # newly selected counters. _handle_source_changes() clears only those
        # transient values.
        if source_changed:
            self.state.restored_from_history = False
            self.state.restored_at = None

        if self.house_entity is None:
            self._clear_house_analysis_state()

        self._remove_timer = async_track_time_change(
            self.hass,
            self._async_quarter_hour,
            minute=[0, 15, 30, 45],
            second=5,
        )

        await self._store.async_save(asdict(self.state))

    async def async_shutdown(self) -> None:
        if self._remove_timer is not None:
            self._remove_timer()
            self._remove_timer = None
        await self._store.async_save(asdict(self.state))

    @callback
    def async_add_listener(self, listener) -> callable:
        self.listeners.append(listener)

        @callback
        def remove_listener() -> None:
            if listener in self.listeners:
                self.listeners.remove(listener)

        return remove_listener

    @callback
    def _notify(self) -> None:
        for listener in list(self.listeners):
            listener()

    def _handle_source_changes(self, now: datetime) -> bool:
        """Apply newly selected source entities without resetting monthly peaks.

        A source change invalidates the current energy baseline because the old
        and new cumulative counters are unrelated. The next quarter-hour
        boundary creates a fresh baseline; the following complete quarter hour
        produces the first new value. Monthly peak values remain untouched.
        """
        grid_changed = self.state.configured_grid_energy != self.grid_entity
        house_changed = self.state.configured_house_energy != self.house_entity

        if not grid_changed and not house_changed:
            return False

        if grid_changed:
            self.state.configured_grid_energy = self.grid_entity
            self.state.grid_source_changed_at = now.isoformat()
        if house_changed:
            self.state.configured_house_energy = self.house_entity
            self.state.house_source_changed_at = now.isoformat()

        # Do not carry a partially completed interval across source changes.
        self.state.last_timestamp = None
        self.state.last_grid_energy_kwh = None
        self.state.last_house_energy_kwh = None
        self.state.grid_power_kw = None
        self.state.house_power_kw = None
        self.state.reduction_kw = None
        self.state.reduction_percent = None
        self.state.interval_start = None
        self.state.interval_end = None
        return True

    def _energy_kwh(self, entity_id: str | None) -> float | None:
        if not entity_id:
            return None
        state = self.hass.states.get(entity_id)
        if state is None or state.state in {"unknown", "unavailable"}:
            return None
        try:
            value = float(state.state)
        except (TypeError, ValueError):
            return None
        unit = state.attributes.get("unit_of_measurement")
        if unit == UnitOfEnergy.WATT_HOUR:
            return value / 1000
        if unit == UnitOfEnergy.KILO_WATT_HOUR:
            return value
        if unit == UnitOfEnergy.MEGA_WATT_HOUR:
            return value * 1000
        return None

    def _history_entity_id(self, object_id: str) -> str:
        """Return the expected Recorder entity ID for the configured prefix."""
        if not self.name_prefix:
            return f"sensor.{object_id}"
        return f"sensor.{slugify(self.name_prefix)}_{object_id}"

    async def _async_restore_from_recorder(self, now: datetime) -> bool:
        """Restore this month's published values after delete/re-add.

        Recorder history is keyed by entity_id and survives removal of the
        config entry. We deliberately restore only published result/peak
        values. The energy baseline is NOT reconstructed, so a re-added
        integration still waits for a new baseline and then one complete
        15-minute interval before calculating fresh data.
        """
        month_start_local = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        start_utc = dt_util.as_utc(month_start_local)
        end_utc = dt_util.as_utc(now)
        history_fields = HISTORY_FIELD_OBJECT_IDS
        if self.house_entity is None:
            # In grid-only mode restore only values that are meaningful without
            # a house-consumption source. Historical house/reduction values may
            # still exist in Recorder from an earlier configuration, but must
            # not become active state for a grid-only instance.
            history_fields = {
                field: object_id
                for field, object_id in HISTORY_FIELD_OBJECT_IDS.items()
                if field in {"grid_power_kw", "grid_peak_kw"}
            }

        history_field_entities = {
            field: self._history_entity_id(object_id)
            for field, object_id in history_fields.items()
        }
        entity_ids = list(dict.fromkeys(history_field_entities.values()))

        try:
            states_by_entity = await self.hass.async_add_executor_job(
                partial(
                    history.get_significant_states,
                    self.hass,
                    start_utc,
                    end_utc,
                    entity_ids,
                    None,
                    False,  # include_start_time_state
                    False,  # significant_changes_only
                    False,  # minimal_response
                    False,  # no_attributes - needed for interval/peak times
                    False,  # compressed_state_format
                )
            )
        except Exception:  # Recorder unavailable/corrupt must not block setup.
            return False

        restored_any = False
        for field_name, entity_id in history_field_entities.items():
            latest = self._latest_numeric_state(states_by_entity.get(entity_id, []))
            if latest is None:
                continue
            setattr(self.state, field_name, float(latest.state))
            restored_any = True

        # Restore the timestamps/context attributes that were published by the
        # old entities. These are important for a meaningful monthly peak.
        latest_grid_peak = self._latest_numeric_state(states_by_entity.get(self._history_entity_id(GRID_PEAK_OBJECT_ID), []))
        if latest_grid_peak is not None:
            peak_time = latest_grid_peak.attributes.get("peak_time")
            if isinstance(peak_time, str) and peak_time:
                self.state.grid_peak_time = peak_time

        if self.house_entity is not None:
            latest_house_peak = self._latest_numeric_state(
                states_by_entity.get(self._history_entity_id(HOUSE_PEAK_OBJECT_ID), [])
            )
            if latest_house_peak is not None:
                peak_time = latest_house_peak.attributes.get("peak_time")
                if isinstance(peak_time, str) and peak_time:
                    self.state.house_peak_time = peak_time

        latest_interval = self._latest_numeric_state(states_by_entity.get(self._history_entity_id(CURRENT_INTERVAL_OBJECT_ID), []))
        if latest_interval is not None:
            interval_start = latest_interval.attributes.get("interval_start")
            interval_end = latest_interval.attributes.get("interval_end")
            if isinstance(interval_start, str) and interval_start:
                self.state.interval_start = interval_start
            if isinstance(interval_end, str) and interval_end:
                self.state.interval_end = interval_end

        if not restored_any:
            return False

        self.state.peak_month = now.strftime("%Y-%m")
        self.state.restored_from_history = True
        self.state.restored_at = now.isoformat()

        # Critical: do not reuse a historical energy baseline. The next
        # quarter-hour boundary establishes a fresh baseline; only the
        # following complete quarter hour can create a new measurement.
        self.state.last_timestamp = None
        self.state.last_grid_energy_kwh = None
        self.state.last_house_energy_kwh = None
        return True

    @staticmethod
    def _latest_numeric_state(states: list[State | dict[str, Any]]) -> State | None:
        """Return the latest State with a numeric value."""
        for item in reversed(states):
            if not isinstance(item, State):
                continue
            if item.state in {"unknown", "unavailable", "none", "None"}:
                continue
            try:
                float(item.state)
            except (TypeError, ValueError):
                continue
            return item
        return None

    async def _async_quarter_hour(self, now: datetime) -> None:
        grid = self._energy_kwh(self.grid_entity)
        house = self._energy_kwh(self.house_entity) if self.house_entity else None
        if grid is None or (self.house_entity is not None and house is None):
            self.state.invalid_intervals += 1
            await self._store.async_save(asdict(self.state))
            self._notify()
            return

        now = dt_util.as_local(now).replace(microsecond=0)
        current_month = now.strftime("%Y-%m")
        if self.state.peak_month != current_month:
            self._reset_month(current_month)

        if self.state.last_timestamp is None:
            self._set_baseline(now, grid, house)
            await self._store.async_save(asdict(self.state))
            self._notify()
            return

        previous_time = datetime.fromisoformat(self.state.last_timestamp)
        elapsed = (now - previous_time).total_seconds()
        expected = INTERVAL_MINUTES * 60
        valid_elapsed = abs(elapsed - expected) <= MAX_INTERVAL_DRIFT_SECONDS

        delta_grid = grid - (self.state.last_grid_energy_kwh or 0)
        delta_house = None
        if self.house_entity is not None:
            delta_house = house - (self.state.last_house_energy_kwh or 0)

        valid_delta = delta_grid >= 0 and (delta_house is None or delta_house >= 0)

        if not valid_elapsed or not valid_delta:
            self.state.invalid_intervals += 1
            self._set_baseline(now, grid, house)
            await self._store.async_save(asdict(self.state))
            self._notify()
            return

        grid_kw = round(delta_grid / INTERVAL_HOURS, 3)
        house_kw = None
        reduction_kw = None
        reduction_percent = None
        if delta_house is not None:
            house_kw = round(delta_house / INTERVAL_HOURS, 3)
            reduction_kw = round(max(house_kw - grid_kw, 0.0), 3)
            reduction_percent = (
                round((reduction_kw / house_kw * 100.0), 1) if house_kw > 0 else 0.0
            )

        self.state.grid_power_kw = grid_kw
        self.state.house_power_kw = house_kw
        self.state.reduction_kw = reduction_kw
        self.state.reduction_percent = reduction_percent
        self.state.interval_start = previous_time.isoformat()
        self.state.interval_end = now.isoformat()

        if self.state.grid_peak_kw is None or grid_kw > self.state.grid_peak_kw:
            self.state.grid_peak_kw = grid_kw
            self.state.grid_peak_time = now.isoformat()
            self.state.grid_peak_house_kw = house_kw
            self.state.grid_peak_reduction_kw = reduction_kw
            self.state.grid_peak_reduction_percent = reduction_percent

        if house_kw is not None and (
            self.state.house_peak_kw is None or house_kw > self.state.house_peak_kw
        ):
            self.state.house_peak_kw = house_kw
            self.state.house_peak_time = now.isoformat()
            self.state.house_peak_grid_kw = grid_kw
            self.state.house_peak_reduction_kw = reduction_kw
            self.state.house_peak_reduction_percent = reduction_percent

        self._set_baseline(now, grid, house)
        await self._store.async_save(asdict(self.state))
        self._notify()

    def _set_baseline(self, now: datetime, grid: float, house: float | None) -> None:
        self.state.last_timestamp = now.isoformat()
        self.state.last_grid_energy_kwh = grid
        self.state.last_house_energy_kwh = house if self.house_entity is not None else None

    def _clear_house_analysis_state(self) -> None:
        """Clear values that require an optional house-consumption source."""
        self.state.last_house_energy_kwh = None
        self.state.house_power_kw = None
        self.state.reduction_kw = None
        self.state.reduction_percent = None
        self.state.grid_peak_house_kw = None
        self.state.grid_peak_reduction_kw = None
        self.state.grid_peak_reduction_percent = None
        self.state.house_peak_kw = None
        self.state.house_peak_time = None
        self.state.house_peak_grid_kw = None
        self.state.house_peak_reduction_kw = None
        self.state.house_peak_reduction_percent = None

    def _reset_month(self, current_month: str) -> None:
        self.state.peak_month = current_month
        self.state.grid_peak_kw = None
        self.state.grid_peak_time = None
        self.state.grid_peak_house_kw = None
        self.state.grid_peak_reduction_kw = None
        self.state.grid_peak_reduction_percent = None
        self.state.house_peak_kw = None
        self.state.house_peak_time = None
        self.state.house_peak_grid_kw = None
        self.state.house_peak_reduction_kw = None
        self.state.house_peak_reduction_percent = None
        self.state.restored_from_history = False
        self.state.restored_at = None
